baseURL = 'https://blog.midstall.com'
languageCode = 'en-us'
title = "Midstall Software's Blog"
enableRobotsTXT = true
enableGitInfo = true

[[module.imports]]
path = 'github.com/526avijitgupta/gokarna'

[[menu.main]]
identifier = 'home'
url = 'https://midstall.com'
name = 'Home'
weight = 1

[[menu.main]]
identifier = 'posts'
url = '/posts/'
name = 'Posts'
weight = 2

[[menu.main]]
identifier = 'github'
url = 'https://github.com/MidstallSoftware'
weight = 3
pre = '<span data-feather="github"></span>'
