baseURL = 'https://blog.midstall.com'
languageCode = 'en-us'
title = "Midstall Software's Blog"
enableRobotsTXT = true

[[module.imports]]
path = 'github.com/526avijitgupta/gokarna'

[params]
description = 'The official blog for Midstall Software.'
socialIcons = [
  { name = 'twitter', url = 'https://twitter.com/MidstallSW' },
  { name = 'github', url = 'https://github.com/MidstallSoftware' },
  { name = 'discord', url = 'https://discord.gg/3kPk9ZU6Da' },
]

[[menu.main]]
name = 'Home'
pre = '<span data-feather="home"></span>'
url = 'https://midstall.com'
weight = 1

[[menu.main]]
name = 'Posts'
pre = "<span data-feather='book'></span>"
url = '/posts/'
weight = 2

[[menu.main]]
name = 'Tags'
pre = '<span data-feather="tag"></span>'
url = '/tags/'
weight = 3

[[menu.main]]
identifier = 'rss'
pre = '<span data-feather="rss"></span>'
url = '/index.xml'
weight = 4

[markup.tableOfContents]
startLevel = 1
endLevel = 4
ordered = false
